#!/bin/bash
set -e
if [ -f /etc/nginx/sites-available/easy-check-web ]; then
    ln -sf /etc/nginx/sites-available/easy-check-web /etc/nginx/sites-enabled/easy-check-web
    nginx -t
    systemctl restart nginx
fi